import { UserNavbar } from "@/components/navbar/user";
import SessionProvider from "@/components/session/session-provider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { getServerSession } from "../lib/auth/server-session-auth";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = getServerSession();

  return (
    <SessionProvider initialSession={session}>
      <html lang="en" data-theme="cupcake">
        <body className={inter.className}>
          <div className="navbar bg-base-100">
            <div className="navbar-start">
              <div className="dropdown">
                <div
                  tabIndex={0}
                  role="button"
                  className="btn btn-ghost lg:hidden"
                >
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    className="h-5 w-5"
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke="currentColor"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth="2"
                      d="M4 6h16M4 12h8m-8 6h16"
                    />
                  </svg>
                </div>
              </div>
              <a className="btn btn-ghost text-xl">daisyUI</a>
            </div>
            <div className="navbar-center hidden lg:flex"></div>
            <div className="navbar-end gap-2">
              <UserNavbar />
            </div>
          </div>
          <section>{children}</section>
        </body>
      </html>
    </SessionProvider>
  );
}
